# Generated by Django 3.2.9 on 2021-12-01 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('def_first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('def_last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('def_email', models.EmailField(blank=True, max_length=50, null=True)),
                ('def_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('def_street', models.CharField(blank=True, max_length=100, null=True)),
                ('def_town', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
