# Generated by Django 3.2.9 on 2021-11-04 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_key',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
