# Generated by Django 3.2.9 on 2021-11-08 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_product_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='artist_key',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
