# Generated by Django 3.2.9 on 2021-12-04 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20211204_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='artist_description',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
