# Generated by Django 3.2.9 on 2021-12-12 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_artist_artist_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='artist_tags',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_tags',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
